spring:
  application:
    name: heythere-community-server
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        - localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
  api-docs:
    enabled: true

cloud:
  aws:
    credentials:
      accessKey: AKIAJF2FHSSU7QJJMHXA
      secretKey: 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
    s3:
      bucket: heythere-file-store
    region:
      static: ap-northeast-2
    stack:
      auto: false

